name: Build and release

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none


jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cross
      - run: cross build --target x86_64-unknown-freebsd --release
      - run: cross build --release

      - name: Release
        if: github.repository_owner == 'myridia'                  
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/x86_64-unknown-freebsd/release/serversite-gen'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true




